// Static airport data — covers major airports used in travel groups
// Format: [IATA, City, Country, Name]

const AIRPORTS: [string, string, string, string][] = [
  // Brasil
  ['GRU', 'São Paulo', 'BR', 'Guarulhos Internacional'],
  ['CGH', 'São Paulo', 'BR', 'Congonhas'],
  ['VCP', 'Campinas', 'BR', 'Viracopos'],
  ['GIG', 'Rio de Janeiro', 'BR', 'Galeão Internacional'],
  ['SDU', 'Rio de Janeiro', 'BR', 'Santos Dumont'],
  ['BSB', 'Brasília', 'BR', 'Juscelino Kubitschek'],
  ['CNF', 'Belo Horizonte', 'BR', 'Confins Internacional'],
  ['PLU', 'Belo Horizonte', 'BR', 'Pampulha'],
  ['SSA', 'Salvador', 'BR', 'Deputado Luís Eduardo Magalhães'],
  ['REC', 'Recife', 'BR', 'Guararapes Internacional'],
  ['FOR', 'Fortaleza', 'BR', 'Pinto Martins'],
  ['POA', 'Porto Alegre', 'BR', 'Salgado Filho'],
  ['CWB', 'Curitiba', 'BR', 'Afonso Pena'],
  ['FLN', 'Florianópolis', 'BR', 'Hercílio Luz'],
  ['NAT', 'Natal', 'BR', 'São Gonçalo do Amarante'],
  ['MCZ', 'Maceió', 'BR', 'Zumbi dos Palmares'],
  ['BEL', 'Belém', 'BR', 'Val de Cans'],
  ['MAO', 'Manaus', 'BR', 'Eduardo Gomes'],
  ['VIX', 'Vitória', 'BR', 'Eurico de Aguiar Salles'],
  ['GYN', 'Goiânia', 'BR', 'Santa Genoveva'],
  ['CGB', 'Cuiabá', 'BR', 'Marechal Rondon'],
  ['CGR', 'Campo Grande', 'BR', 'Internacional de Campo Grande'],
  ['SLZ', 'São Luís', 'BR', 'Marechal Cunha Machado'],
  ['THE', 'Teresina', 'BR', 'Senador Petrônio Portella'],
  ['AJU', 'Aracaju', 'BR', 'Santa Maria'],
  ['JPA', 'João Pessoa', 'BR', 'Presidente Castro Pinto'],
  ['PMW', 'Palmas', 'BR', 'Brigadeiro Lysias Rodrigues'],
  ['PVH', 'Porto Velho', 'BR', 'Governador Jorge Teixeira'],
  ['MCP', 'Macapá', 'BR', 'Alberto Alcolumbre'],
  ['BVB', 'Boa Vista', 'BR', 'Atlas Brasil Cantanhede'],
  ['RBR', 'Rio Branco', 'BR', 'Plácido de Castro'],
  ['IGU', 'Foz do Iguaçu', 'BR', 'Cataratas Internacional'],
  ['NVT', 'Navegantes', 'BR', 'Ministro Victor Konder'],
  ['JOI', 'Joinville', 'BR', 'Lauro Carneiro de Loyola'],
  ['LDB', 'Londrina', 'BR', 'Governador José Richa'],
  ['MGF', 'Maringá', 'BR', 'Sílvio Name Júnior'],
  ['UDI', 'Uberlândia', 'BR', 'Ten. Cel. Aviador César Bombonato'],
  ['RAO', 'Ribeirão Preto', 'BR', 'Dr. Leite Lopes'],
  ['SJP', 'São José do Rio Preto', 'BR', 'Prof. Eribelto Manoel Reino'],
  ['PPB', 'Presidente Prudente', 'BR', 'Presidente Prudente'],
  ['BAU', 'Bauru', 'BR', 'Bauru-Arealva'],
  ['IOS', 'Ilhéus', 'BR', 'Jorge Amado'],
  ['BPS', 'Porto Seguro', 'BR', 'Porto Seguro'],
  ['LEC', 'Lençóis', 'BR', 'Chapada Diamantina'],
  ['FEN', 'Fernando de Noronha', 'BR', 'Fernando de Noronha'],
  ['CPV', 'Campina Grande', 'BR', 'Presidente João Suassuna'],
  ['STM', 'Santarém', 'BR', 'Maestro Wilson Fonseca'],
  ['JDO', 'Juazeiro do Norte', 'BR', 'Orlando Bezerra de Menezes'],
  ['IMP', 'Imperatriz', 'BR', 'Prefeito Renato Moreira'],
  ['CXJ', 'Caxias do Sul', 'BR', 'Hugo Cantergiani'],
  ['PFB', 'Passo Fundo', 'BR', 'Lauro Kortz'],
  ['PET', 'Pelotas', 'BR', 'Internacional de Pelotas'],

  // América do Sul
  ['EZE', 'Buenos Aires', 'AR', 'Ezeiza Ministro Pistarini'],
  ['AEP', 'Buenos Aires', 'AR', 'Aeroparque Jorge Newbery'],
  ['SCL', 'Santiago', 'CL', 'Arturo Merino Benítez'],
  ['LIM', 'Lima', 'PE', 'Jorge Chávez'],
  ['BOG', 'Bogotá', 'CO', 'El Dorado'],
  ['UIO', 'Quito', 'EC', 'Mariscal Sucre'],
  ['GYE', 'Guayaquil', 'EC', 'José Joaquín de Olmedo'],
  ['CCS', 'Caracas', 'VE', 'Simón Bolívar'],
  ['MVD', 'Montevidéu', 'UY', 'Carrasco'],
  ['ASU', 'Assunção', 'PY', 'Silvio Pettirossi'],
  ['VVI', 'Santa Cruz', 'BO', 'Viru Viru'],
  ['LPB', 'La Paz', 'BO', 'El Alto'],
  ['PTY', 'Cidade do Panamá', 'PA', 'Tocumen'],
  ['SJO', 'San José', 'CR', 'Juan Santamaría'],
  ['CUZ', 'Cusco', 'PE', 'Alejandro Velasco Astete'],
  ['MDE', 'Medellín', 'CO', 'José María Córdova'],
  ['CTG', 'Cartagena', 'CO', 'Rafael Núñez'],
  ['COR', 'Córdoba', 'AR', 'Ingeniero Ambrosio Taravella'],
  ['MDZ', 'Mendoza', 'AR', 'El Plumerillo'],
  ['BRC', 'Bariloche', 'AR', 'Teniente Luis Candelaria'],
  ['IGR', 'Puerto Iguazú', 'AR', 'Cataratas del Iguazú'],
  ['USH', 'Ushuaia', 'AR', 'Malvinas Argentinas'],
  ['FTE', 'El Calafate', 'AR', 'Comandante Armando Tola'],
  ['PUQ', 'Punta Arenas', 'CL', 'Carlos Ibáñez del Campo'],

  // América do Norte
  ['MIA', 'Miami', 'US', 'Miami International'],
  ['JFK', 'Nova York', 'US', 'John F. Kennedy'],
  ['EWR', 'Newark', 'US', 'Newark Liberty'],
  ['LAX', 'Los Angeles', 'US', 'Los Angeles International'],
  ['ORD', 'Chicago', 'US', "O'Hare International"],
  ['ATL', 'Atlanta', 'US', 'Hartsfield-Jackson'],
  ['DFW', 'Dallas', 'US', 'Dallas/Fort Worth'],
  ['IAH', 'Houston', 'US', 'George Bush Intercontinental'],
  ['SFO', 'São Francisco', 'US', 'San Francisco International'],
  ['MCO', 'Orlando', 'US', 'Orlando International'],
  ['BOS', 'Boston', 'US', 'Logan International'],
  ['DCA', 'Washington', 'US', 'Ronald Reagan'],
  ['IAD', 'Washington', 'US', 'Dulles International'],
  ['LAS', 'Las Vegas', 'US', 'Harry Reid International'],
  ['SEA', 'Seattle', 'US', 'Seattle-Tacoma'],
  ['DEN', 'Denver', 'US', 'Denver International'],
  ['PHX', 'Phoenix', 'US', 'Phoenix Sky Harbor'],
  ['MEX', 'Cidade do México', 'MX', 'Benito Juárez'],
  ['CUN', 'Cancún', 'MX', 'Cancún Internacional'],
  ['YYZ', 'Toronto', 'CA', 'Toronto Pearson'],
  ['YUL', 'Montreal', 'CA', 'Pierre Elliott Trudeau'],
  ['YVR', 'Vancouver', 'CA', 'Vancouver International'],
  ['HAV', 'Havana', 'CU', 'José Martí'],

  // Europa
  ['LIS', 'Lisboa', 'PT', 'Humberto Delgado'],
  ['OPO', 'Porto', 'PT', 'Francisco Sá Carneiro'],
  ['MAD', 'Madrid', 'ES', 'Adolfo Suárez Madrid-Barajas'],
  ['BCN', 'Barcelona', 'ES', 'El Prat'],
  ['CDG', 'Paris', 'FR', 'Charles de Gaulle'],
  ['ORY', 'Paris', 'FR', 'Orly'],
  ['LHR', 'Londres', 'GB', 'Heathrow'],
  ['LGW', 'Londres', 'GB', 'Gatwick'],
  ['STN', 'Londres', 'GB', 'Stansted'],
  ['FCO', 'Roma', 'IT', 'Fiumicino'],
  ['MXP', 'Milão', 'IT', 'Malpensa'],
  ['VCE', 'Veneza', 'IT', 'Marco Polo'],
  ['FLR', 'Florença', 'IT', 'Amerigo Vespucci'],
  ['NAP', 'Nápoles', 'IT', 'Capodichino'],
  ['AMS', 'Amsterdã', 'NL', 'Schiphol'],
  ['FRA', 'Frankfurt', 'DE', 'Frankfurt Airport'],
  ['MUC', 'Munique', 'DE', 'Franz Josef Strauss'],
  ['ZRH', 'Zurique', 'CH', 'Zurich Airport'],
  ['GVA', 'Genebra', 'CH', 'Genève-Cointrin'],
  ['VIE', 'Viena', 'AT', 'Vienna International'],
  ['PRG', 'Praga', 'CZ', 'Václav Havel'],
  ['BUD', 'Budapeste', 'HU', 'Budapest Ferenc Liszt'],
  ['WAW', 'Varsóvia', 'PL', 'Chopin'],
  ['ATH', 'Atenas', 'GR', 'Eleftherios Venizelos'],
  ['IST', 'Istambul', 'TR', 'Istanbul Airport'],
  ['DUB', 'Dublin', 'IE', 'Dublin Airport'],
  ['CPH', 'Copenhague', 'DK', 'Kastrup'],
  ['ARN', 'Estocolmo', 'SE', 'Arlanda'],
  ['OSL', 'Oslo', 'NO', 'Gardermoen'],
  ['HEL', 'Helsinque', 'FI', 'Helsinki-Vantaa'],
  ['BRU', 'Bruxelas', 'BE', 'Brussels Airport'],
  ['EDI', 'Edimburgo', 'GB', 'Edinburgh Airport'],

  // Oriente Médio / África
  ['DXB', 'Dubai', 'AE', 'Dubai International'],
  ['DOH', 'Doha', 'QA', 'Hamad International'],
  ['TLV', 'Tel Aviv', 'IL', 'Ben Gurion'],
  ['JNB', 'Joanesburgo', 'ZA', 'O.R. Tambo'],
  ['CPT', 'Cidade do Cabo', 'ZA', 'Cape Town International'],
  ['CAI', 'Cairo', 'EG', 'Cairo International'],
  ['CMN', 'Casablanca', 'MA', 'Mohammed V'],
  ['ADD', 'Addis Abeba', 'ET', 'Bole International'],
  ['NBO', 'Nairóbi', 'KE', 'Jomo Kenyatta'],

  // Ásia / Oceania
  ['NRT', 'Tóquio', 'JP', 'Narita'],
  ['HND', 'Tóquio', 'JP', 'Haneda'],
  ['ICN', 'Seul', 'KR', 'Incheon'],
  ['PEK', 'Pequim', 'CN', 'Capital International'],
  ['PVG', 'Xangai', 'CN', 'Pudong'],
  ['HKG', 'Hong Kong', 'HK', 'Hong Kong International'],
  ['SIN', 'Cingapura', 'SG', 'Changi'],
  ['BKK', 'Bangkok', 'TH', 'Suvarnabhumi'],
  ['DEL', 'Nova Délhi', 'IN', 'Indira Gandhi'],
  ['BOM', 'Mumbai', 'IN', 'Chhatrapati Shivaji'],
  ['SYD', 'Sydney', 'AU', 'Kingsford Smith'],
  ['MEL', 'Melbourne', 'AU', 'Tullamarine'],
  ['AKL', 'Auckland', 'NZ', 'Auckland Airport'],

  // Caribe
  ['SDQ', 'Santo Domingo', 'DO', 'Las Américas'],
  ['PUJ', 'Punta Cana', 'DO', 'Punta Cana International'],
  ['SXM', 'Saint Martin', 'SX', 'Princess Juliana'],
  ['MBJ', 'Montego Bay', 'JM', 'Sangster International'],
  ['NAS', 'Nassau', 'BS', 'Lynden Pindling'],
  ['AUA', 'Aruba', 'AW', 'Queen Beatrix'],
  ['CUR', 'Curaçao', 'CW', 'Hato International'],
  ['BON', 'Bonaire', 'BQ', 'Flamingo International'],
  ['SJU', 'San Juan', 'PR', 'Luis Muñoz Marín'],
];

export interface AirportOption {
  iataCode: string;
  name: string;
  cityName: string;
  countryCode: string;
}

export function searchAirports(keyword: string): AirportOption[] {
  const kw = keyword.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  return AIRPORTS
    .filter(([iata, city, , name]) => {
      const norm = (s: string) => s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
      return iata.toLowerCase().includes(kw) || norm(city).includes(kw) || norm(name).includes(kw);
    })
    .slice(0, 15)
    .map(([iata, city, country, name]) => ({
      iataCode: iata,
      name,
      cityName: city,
      countryCode: country,
    }));
}
